name: Sync Nextcloud Files

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual execution

jobs:
  fetch-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Files from Nextcloud
        run: |
          curl -o filterlist.txt "https://kim.nl.tab.digital/s/BxfidAJbrX2MEWD/download/filterlist.txt"
          curl -o filters/ads.txt "https://kim.nl.tab.digital/s/RAsbYmQBj43btRi/download/ads.txt"
          curl -o filters/gambling.txt "https://kim.nl.tab.digital/s/4QZMc8K7aJwYSoB/download/gambling.txt"
          curl -o filters/annoyances.txt "https://kim.nl.tab.digital/s/tiNB9TyksoatPWF/download/annoyances.txt"
          curl -o filters/tracking.txt "https://kim.nl.tab.digital/s/ipsq8zySZGqBqbY/download/tracking.txt"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-fetch from Nextcloud" || echo "No changes to commit"
          git push
